spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/corp_platform
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379
